# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalreport',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Active users'), (1, 'User risk scores'), (2, 'Quarter validation'), (3, 'Goals'), (4, 'Recurrent orders'), (5, 'Orders'), (6, 'Balances')]),
        ),
    ]
